### ISSUE TITLE
取消按钮取消时有bug

### ISSUE THREAD

**Issue by no13bus** [tsrot/react-zhihu#4]
如果帖子有title和des的时候，这个时候点击取消按钮，不发表帖子的话，还是会在QuestionList出来。
应该是取消按钮也触动了submit事件。建议:

将
```
<button className="btn btn-default pull-right" onClick={this.props.onToggleForm}>取消</button >
```

改成
```
<span className="btn btn-default pull-right" onClick={this.props.onToggleForm}>取消</span>
```

**Comment by tsrot** [comment]
谢谢你的建议，已经改了。
主要问题是button标签没有加上type属性。在w3c标准中，当button未加上type属性时，默认type为submit。所以只需要给button加上type=“button”就好。

**Comment by no13bus** [comment]
赞！学习了。原来有这么个属性。
